baseURL = 'https://www.dazfuller.uk/'
languageCode = 'en-gb'
title = 'reality.foldLeft'
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
sectionPagesMenu = 'main'
enableEmoji = true
enableRobotsTXT = true

[params.ananke.social.mastodon]
profilelink = 'https://mstdn.social/@dazfuller'

[params.ananke.social.bluesky]
profilelink = 'https://bsky.app/profile/dazfuller.bsky.social'

[params.ananke.social.linkedin]
username = "dazfuller"

[params.ananke.social.github]
username = 'dazfuller'

[params.ananke.social.rss]
profilelink = '/index.xml#feed'

[[params.author]]
  email = 'contact@dazfuller.uk'
  name = 'Darren Fuller'
