name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  HUGO_VERSION: 0.140.0

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build And Deploy
        run: |
          npm install -g @azure/static-web-apps-cli
          rm -rf ./public
          hugo
          swa deploy -a ./ -O ./public --env Production -d ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_BAY_0B863B003 }}
